name: squad
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - ujson
  - numpy
  - pip
  - spacy=2.0.16
  - tensorboard
  - tensorflow
  - tqdm
  - urllib3
  - pytorch=1.5
  - cudatoolkit=10.2
  - requests
  