name: squad
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - ujson
  - numpy
  - pip
  - spacy
  - tensorboard
  # - tensorflow
  - tqdm
  - urllib3
  - pytorch
  - cudatoolkit=10.2
  - requests
  - black
  - nb_conda
  - jupyter_contrib_nbextensions
  - python-dotenv
  - click
  